/*!
 * \file Engine_Enum.h
 * \date 2015/04/05 8:42
 *
 * \author Administrator
 * Contact: user@company.com
 *
 * \brief 
 *
 * TODO: long description
 *
 * \note
*/
#ifndef Engine_Enum_h__
#define Engine_Enum_h__

namespace Engine
{
	const WORD		WINCX = 1680;
	const WORD		WINCY = 1050;

	enum ANGLE {ANGLE_X, ANGLE_Y, ANGLE_Z, ANGLE_END,};
	enum TEXTURETYPE { TEXTURE_NORMAL, TEXTURE_BUMP, TEXTURE_CUBE };
	enum MESHTYPE {MESH_STATIC, MESH_DYNAMIC, MESH_EFFECT};
	enum PARTICLE_SHAPE {SHAPE_CIRCLE, SHAPE_BOX, SHAPE_SPHERE, SHAPE_CONE };
	enum EFFECT_ACTION {ACT_POS, ACT_ROT, ACT_SCALE, ACT_FADE, ACT_UV, ACT_UVSIZE, ACT_COLOR, ACT_END };
	enum CELLTYPE {TYPE_TERRAIN, TYPE_CELL, TYPE_MESH, TYPE_END};

	//¿Ã∆Â∆Æ
	enum GUARDIAN_FX {G_SKILL1, G_SKILL1_TARGET, G_SKILL2, G_SKILL2_ROOT, G_SKILL3, G_SKILL4, G_SKILL4_SUB, G_SKILL5, G_DASH, G_INNATE, G_END};
	enum RANGER_FX {R_SKILL1, R_SKILL2, R_SKILL3, R_SKILL4, R_SKILL5, R_DASH, R_INNATE, R_DEFAULT, R_SKILL2_ARROW, R_SKILL2_BODY, R_SKILL3_ARROW, R_SKILL3_TARGETHIT, R_SKILL5_TARGETHIT, R_SKILLSHOT, R_END};
	enum MAGICIAN_FX {M_SKILL1, M_SKILL2, M_SKILL3, M_SKILL4, M_SKILL5, M_INNATE, M_DEFAULT, M_DEFAULT_2_FIRST, M_DEFAULT_2_SECOND, M_DEFAULT1, M_SKILL4_FLOOR, M_END };
	enum PALADIN_FX {P_SKILL1, P_SKILL1_SUB, P_SKILL1_TARGET, P_SKILL1_WEAPON, P_SKILL2, P_SKILL2_BODY, P_SKILL3, P_SKILL3_TARGET, P_SKILL4, P_SKILL4_TARGET, P_SKILL5, P_DASH, P_DASH_TARGET, P_INNATE, P_END};
	enum MONSTER_FX {SKULL_EXPLO, SKULL_SUMMON, SKULL_SUMMON_TARGET, SKULL_SLASH, SKULL_THORN, SKULL_ORA, SPIDER_SMOKE, SPIDER_SMOKE_FLOOR, SPIDER_EXPLO, SKULL_FIREEXPLO, SKULL_FIREEXPLO2, SKULL_FIREEXPLOSINGLE, SKULL_THORN_FLOOR, SKULL_METEO, SKULL_SHIELD, MONSTER_END};
	enum ETC_FX {ETC_TARGET, ETC_PLAYTARGET, ETC_HIT, ETC_HIT2, ETC_HITCIRCLE, ETC_HITBLOOD, ETC_HITSLASH, ETC_TARGETSELECT, ETC_SMOKE, ETC_QUEST, ETC_TORCH, ETC_PORTAL, ETC_QUESTPOINT, ETC_NAVIARROW_BLUE, ETC_NAVIARROW_ORANGE, ETC_NAVIARROW_RED, ETC_NAVIBODY, ETC_STARPOINT, ETC_CASTLEMETEO, ETC_END};
	enum TRAIL_FX{TRAIL_SWORD, TRAIL_MACE, TRAIL_END};
}

#endif // Engine_Enum_h__