#ifndef Enum_h__
#define Enum_h__

enum RESOURCETYPE {RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_STATIC, RESOURCE_UI, RESOURCE_REMAIN, RESOURCE_END};
enum CELLTYPE {TYPE_TERRAIN, TYPE_CELL, TYPE_MESH, TYPE_END};
enum STAGETYPE { ST_STAGE1, ST_STAGE2, ST_END };
enum LAYERID {/*LAYER_ENVIRONMENT, */LAYER_GAMELOGIC, LAYER_UI, LAYER_EFFECT};

#endif // Enum_h__